### ISSUE TITLE
poor usability of some functions

### ISSUE THREAD

**Issue by c-cube** [johnelse/ocaml-irc-client#11]
Some functions in `Irc_client` require many not-that-useful arguments, by name. For instance, `Irc_client.connect` requires 6 parameters, including `realname`, `username`, `mode` (?) -- those could probably have sane default values?

That might be a matter of taste, but in general I feel there are too many named parameters (e.g., parameters to the callback to `Irc_client.listen` do not have to be named ones).

Why is there an indirection `Irc_client_lwt.Client`, rather than juste functions in `Irc_client_lwt`? This seems quite redundant.

I'm working on a more precise parsing of messages (related to #9).

**Comment by johnelse** [comment]
> Some functions in Irc_client require many not-that-useful arguments, by name. For instance, Irc_client.connect requires 6 parameters, including realname, username, mode (?) -- those could probably have sane default values?

Yep, makes sense.

> That might be a matter of taste, but in general I feel there are too many named parameters (e.g., parameters to the callback to Irc_client.listen do not have to be named ones).

Fair enough - I do like my named arguments, but I'd happily lose them from the callback.

> Why is there an indirection Irc_client_lwt.Client, rather than juste functions in Irc_client_lwt? This seems quite redundant.

True, not quite sure why I did that now :-)

I'd like to get rid of the unneeded unit arguments to `connect` and `connect_by_name` too.

**Comment by c-cube** [comment]
Branch https://github.com/c-cube/ocaml-irc-client/tree/rfc2812 should fix all my griefs, I think. I will make a PR soon.
