### ISSUE TITLE
listen does not return even if it should timeout

### ISSUE THREAD

**Issue by xapantu** [johnelse/ocaml-irc-client#22]
If for instance I shut down the wifi on my laptop, nothing happens and the examples think they are still connected, even after a reasonable amount of time (> 10 minutes).

The client should probably regularly send a ping request to the server, and timeout after a while without pong command.

There are some ideas in this branch: https://github.com/xapantu/ocaml-irc-client/tree/timeout however this kind of approach will hardly work with the unix transport.

**Comment by c-cube** [comment]
There is already "ping" messages sent from the server, to which the client must answer. I suppose that failing to receive such a message in a sufficiently long time should be enough for disconnecting.

**Comment by johnelse** [comment]
I am thinking of adding an optional argument to `listen`, something like

```
type keepalive = {
  mode: [`Active | `Passive];
  timeout: int;
}
```

`Passive` would check that the server has pinged the client within the last `timeout` seconds.

`Active` would send a client -> server ping every `timeout` seconds, and expect a pong in return.

Thoughts? :-)

**Comment by c-cube** [comment]
If the active behavior is allowed by the RFC, I'm strongly in favor (and it should be the default choice!). In general it's good to detect disconnections.

How about a third field that specified whether to automatically reconnect after `n` seconds?

**Comment by johnelse** [comment]
Ok sounds good.

```
type keepalive = {
  mode: [`Active | `Passive];
  timeout: int;
  reconnect_delay: int option;
}
```

Then if `reconnect_delay` is `None`, `listen` will return on disconnection rather than attempting to reconnect.

**Comment by c-cube** [comment]
Looks good indeed! I also think the default behavior should be active ping + autoreconnect. :)

**Comment by c-cube** [comment]
I checked in https://tools.ietf.org/html/rfc2812#section-3.7.2 : 

> The PING command is used to test the presence of an active client or
   server at the other end of the connection.

looks like it's ok for the client to ping the server.

**Comment by c-cube** [comment]
@johnelse have you written this yet?

**Comment by c-cube** [comment]
I missed the code by @xapantu, sorry, you already had done most of the work :/
I tried something with "active" and "passive" mode, but it's not tested yet.

**Comment by c-cube** [comment]
Note: the last version has somehow more intrusive changes to the API, but its reconnection API seems to work. It provides a `reconnect_loop` function to wrap `connect`+`listen` and reconnects automatically. Please review, this could be useful ;-)

**Comment by c-cube** [comment]
Should this be closed?

**Comment by johnelse** [comment]
Yes :-)
