### ISSUE TITLE
Error: Unbound module Result

### ISSUE THREAD

**Issue by ipavl** [johnelse/ocaml-irc-client#26]
`$ ocamlfind ocamlopt -package irc-client.lwt -linkpkg example1.ml`

```
File "example1.ml", line 22, characters 4-13:
Error: Unbound module Result
```

If I undo the change that #24 introduced to those lines (so that they use \``Ok` and ``Error`, respectively), everything works fine.

Installed via `opam install irc-client`, `ocamlfind` says version 0.3.2.

**Comment by johnelse** [comment]
Hi! Thanks for the report.

At the moment, the `master` branch depends on `result`, but this isn't true for any of the released versions, so if you `opam install irc-client` and then try to build `master` you won't necessarily have all the dependencies.

Try running

```
opam pin add -n irc-client /path/to/local/ocaml-irc-client#master
opam install --deps-only irc-client
```

which will install the dependencies needed to build `master`.

**Comment by ipavl** [comment]
That seems to work - thanks!

**Comment by johnelse** [comment]
No problem :-)
