### ISSUE TITLE
separate opam packages for `irc-client.lwt` and `irc-client.tls`

### ISSUE THREAD

**Issue by c-cube** [johnelse/ocaml-irc-client#32]
Same as [for lwt](https://github.com/ocsigen/lwt/pull/301), would be better to have `irc-client-lwt` and `irc-client-tls` as separate opam packages (still in only one git repo) so that it's easy to `opam install irc-client-tls` and have the dependencies pulled automatically.

**Comment by johnelse** [comment]
Yeah, that sounds like a good idea. It's a bit of a pain that at the moment if you opam install `irc-client` you don't know exactly what you're going to get, unless you've checked the depopts beforehand.

I will try and have a go at this this week (but if you have time yourself feel free :-) ).

**Comment by c-cube** [comment]
heh. I think there's a mechanism in opam for having multiple opam files in the same repo (maybe like "package1.opam", "package2.opam", etc.) so that `opam pin` and `opam publish` are still nice to use.

**Comment by c-cube** [comment]
I think this is closed on master
