### ISSUE TITLE
Invalid reference in irc_helpers.mli

### ISSUE THREAD

**Issue by nbraud** [johnelse/ocaml-irc-client#33]
In https://github.com/johnelse/ocaml-irc-client/commit/e95b33a1bf0623e91c7e027b95220efdb0ef44b7 you removed `split1`, but the [OCamlDoc string](https://github.com/johnelse/ocaml-irc-client/blob/master/lib/irc_helpers.mli#L7) for `split1_exn` still refers to it.

**Comment by johnelse** [comment]
Nice spot, thanks! Fixed in e72114599d70039d02f6240d77c7d1f5d06a5a0f.
