### ISSUE TITLE
PONG command expects only one parameter

### ISSUE THREAD

**Issue by Lyokovic** [johnelse/ocaml-irc-client#38]
Currently, the lib handles PONG IRC commands and expects only one parameter.
The IRC RFC (https://tools.ietf.org/html/rfc2812#section-3.7.3) specifies that it can have two parameters, which is what happens with some servers (seen on some Freenode servers, and ngircd). When there is two parameters, an error is logged:
`failed to parse ":<url> PONG <url> :ping" because: expected one parameter`

I have a quick fix in my branch fix-pong: https://github.com/johnelse/ocaml-irc-client/compare/master...Lyokovic:fix-pong

**Comment by c-cube** [comment]
Can you make this into a PR? I also have some issues with pongs… :/
