### ISSUE TITLE
make a release?

### ISSUE THREAD

**Issue by c-cube** [johnelse/ocaml-irc-client#45]
I think a release with the sub-libraries would be useful (maybe as 0.6?)

**Comment by johnelse** [comment]
Yes :-) I was going to try and fix the code coverage CI etc. but actually it looks like a lot of work, so I'll save it for later.

**Comment by johnelse** [comment]
In progress: https://github.com/ocaml/opam-repository/pull/12233

n.b. I've constrained calculon to irc-client < 0.6.0 to fix the revdeps.

**Comment by johnelse** [comment]
Done :-)
